# Generated by Django 5.2.4 on 2025-11-18 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_size', models.CharField(choices=[('startup', 'Startup (1-50)'), ('small', 'Small (51-200)'), ('medium', 'Medium (201-1000)'), ('large', 'Large (1000+)')], default='startup', max_length=20)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('company_description', models.TextField(blank=True, help_text='About your company', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('headline', models.CharField(blank=True, help_text='Professional headline', max_length=255, null=True)),
                ('bio', models.TextField(blank=True, help_text='About yourself', null=True)),
                ('experience_level', models.CharField(choices=[('fresher', 'Fresher'), ('junior', 'Junior (0-2 years)'), ('mid', 'Mid-level (2-5 years)'), ('senior', 'Senior (5-10 years)'), ('expert', 'Expert (10+ years)')], default='fresher', max_length=20)),
                ('portfolio_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('github_url', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills', null=True)),
                ('preferred_job_types', models.CharField(blank=True, help_text='Comma-separated preferred job types: Full-time, Part-time, Contract, etc.', max_length=255, null=True)),
                ('preferred_locations', models.CharField(blank=True, help_text='Comma-separated preferred locations', max_length=255, null=True)),
                ('expected_salary', models.IntegerField(blank=True, help_text='Expected annual salary', null=True)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker',
                'verbose_name_plural': 'Job Seekers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAccountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Account Created'), ('updated_profile', 'Profile Updated'), ('applied_job', 'Applied to Job'), ('saved_job', 'Saved Job'), ('logged_in', 'Logged In'), ('password_changed', 'Password Changed'), ('email_verified', 'Email Verified'), ('profile_completed', 'Profile Completed')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account History',
                'verbose_name_plural': 'User Account Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
