# Generated by Django 5.2.4 on 2025-11-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer')], default='jobseeker', max_length=20),
        ),
    ]
