# Generated by Django 5.2.4 on 2025-11-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_userprofile_profile_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='application_resumes/'),
        ),
    ]
