# Generated by Django 5.2.4 on 2025-11-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_userprofile_user_type'),
        ('jobs', '0003_alter_application_resume'),
    ]

    operations = [
    ]
