# Generated by Django 5.2.4 on 2025-11-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_merge_20251119_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.CharField(choices=[('fresher', 'Fresher/Entry-level'), ('junior', 'Junior (0-2 years)'), ('mid', 'Mid-level (2-5 years)'), ('senior', 'Senior (5-10 years)'), ('expert', 'Expert (10+ years)')], default='junior', max_length=20),
        ),
    ]
