# Generated by Django 5.2.4 on 2025-12-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_job_experience_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, default=''),
        ),
    ]
